package scientificcalculator;

public class ScientificCalc extends javax.swing.JFrame {

    /**
     * Creates new form ScientificCalc
     */
    public ScientificCalc() {
        initComponents();
        jRadioButton1.setEnabled(false);
    }

    double num1, num2, result;
    String opr;
    @Override
    public void enable() {
        jTextField1.setEnabled(true);
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(true);
        jButton101.setEnabled(true);
        jButton102.setEnabled(true);
        jButton103.setEnabled(true);
        jButton104.setEnabled(true);
        jButton105.setEnabled(true);
        jButton106.setEnabled(true);
        jButton107.setEnabled(true);
        jButton108.setEnabled(true);
        jButton109.setEnabled(true);
        jButton110.setEnabled(true);
        jButton111.setEnabled(true);
        jButton112.setEnabled(true);
        jButton113.setEnabled(true);
        jButton114.setEnabled(true);
        jButton115.setEnabled(true);
        jButton116.setEnabled(true);
        jButton117.setEnabled(true);
        jButton118.setEnabled(true);
        jButton119.setEnabled(true);
        jButton120.setEnabled(true);
        jButton121.setEnabled(true);
        jButton122.setEnabled(true);
        jButton123.setEnabled(true);
        jButton124.setEnabled(true);
        jButton125.setEnabled(true);
        jButton126.setEnabled(true);
        jButton127.setEnabled(true);
        jButton128.setEnabled(true);
        jButton129.setEnabled(true);
        jButton130.setEnabled(true);
        jButton131.setEnabled(true);
        jButton132.setEnabled(true);
        jButton133.setEnabled(true);
        jButton134.setEnabled(true);
    }
    @Override
    public void disable() {
        jTextField1.setEnabled(false);
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(false);
        jButton101.setEnabled(false);
        jButton102.setEnabled(false);
        jButton103.setEnabled(false);
        jButton104.setEnabled(false);
        jButton105.setEnabled(false);
        jButton106.setEnabled(false);
        jButton107.setEnabled(false);
        jButton108.setEnabled(false);
        jButton109.setEnabled(false);
        jButton110.setEnabled(false);
        jButton111.setEnabled(false);
        jButton112.setEnabled(false);
        jButton113.setEnabled(false);
        jButton114.setEnabled(false);
        jButton115.setEnabled(false);
        jButton116.setEnabled(false);
        jButton117.setEnabled(false);
        jButton118.setEnabled(false);
        jButton119.setEnabled(false);
        jButton120.setEnabled(false);
        jButton121.setEnabled(false);
        jButton122.setEnabled(false);
        jButton123.setEnabled(false);
        jButton124.setEnabled(false);
        jButton125.setEnabled(false);
        jButton126.setEnabled(false);
        jButton127.setEnabled(false);
        jButton128.setEnabled(false);
        jButton129.setEnabled(false);
        jButton130.setEnabled(false);
        jButton131.setEnabled(false);
        jButton132.setEnabled(false);
        jButton133.setEnabled(false);
        jButton134.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton102 = new javax.swing.JButton();
        jButton101 = new javax.swing.JButton();
        jButton111 = new javax.swing.JButton();
        jButton116 = new javax.swing.JButton();
        jButton121 = new javax.swing.JButton();
        jButton126 = new javax.swing.JButton();
        jButton131 = new javax.swing.JButton();
        jButton103 = new javax.swing.JButton();
        jButton104 = new javax.swing.JButton();
        jButton105 = new javax.swing.JButton();
        jButton107 = new javax.swing.JButton();
        jButton108 = new javax.swing.JButton();
        jButton109 = new javax.swing.JButton();
        jButton110 = new javax.swing.JButton();
        jButton106 = new javax.swing.JButton();
        jButton112 = new javax.swing.JButton();
        jButton113 = new javax.swing.JButton();
        jButton114 = new javax.swing.JButton();
        jButton115 = new javax.swing.JButton();
        jButton117 = new javax.swing.JButton();
        jButton118 = new javax.swing.JButton();
        jButton120 = new javax.swing.JButton();
        jButton119 = new javax.swing.JButton();
        jButton122 = new javax.swing.JButton();
        jButton123 = new javax.swing.JButton();
        jButton124 = new javax.swing.JButton();
        jButton125 = new javax.swing.JButton();
        jButton127 = new javax.swing.JButton();
        jButton130 = new javax.swing.JButton();
        jButton128 = new javax.swing.JButton();
        jButton129 = new javax.swing.JButton();
        jButton134 = new javax.swing.JButton();
        jButton132 = new javax.swing.JButton();
        jButton133 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scientific Calculator");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setText("ON");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2.setText("OFF");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jButton102.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton102.setText("exp");
        jButton102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton102ActionPerformed(evt);
            }
        });

        jButton101.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton101.setText("sqrt");
        jButton101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton101ActionPerformed(evt);
            }
        });

        jButton111.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton111.setText("x^y");
        jButton111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton111ActionPerformed(evt);
            }
        });

        jButton116.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton116.setText("x^3");
        jButton116.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton116ActionPerformed(evt);
            }
        });

        jButton121.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton121.setText("x^2");
        jButton121.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton121ActionPerformed(evt);
            }
        });

        jButton126.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton126.setText("n!");
        jButton126.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton126ActionPerformed(evt);
            }
        });

        jButton131.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton131.setText("+/-");

        jButton103.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton103.setText("sin");
        jButton103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton103ActionPerformed(evt);
            }
        });

        jButton104.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton104.setText("cos");
        jButton104.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton104ActionPerformed(evt);
            }
        });

        jButton105.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton105.setText("tan");
        jButton105.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton105ActionPerformed(evt);
            }
        });

        jButton107.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton107.setText("log");
        jButton107.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton107ActionPerformed(evt);
            }
        });

        jButton108.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton108.setText("sinh");
        jButton108.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton108ActionPerformed(evt);
            }
        });

        jButton109.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton109.setText("cosh");
        jButton109.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton109ActionPerformed(evt);
            }
        });

        jButton110.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton110.setText("tanh");
        jButton110.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton110ActionPerformed(evt);
            }
        });

        jButton106.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton106.setText("1/x");
        jButton106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton106ActionPerformed(evt);
            }
        });

        jButton112.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton112.setText("%");
        jButton112.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton112ActionPerformed(evt);
            }
        });

        jButton113.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton113.setText("Clr");
        jButton113.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton113ActionPerformed(evt);
            }
        });

        jButton114.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton114.setText("B");
        jButton114.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton114ActionPerformed(evt);
            }
        });

        jButton115.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton115.setText("+");
        jButton115.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton115ActionPerformed(evt);
            }
        });

        jButton117.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton117.setText("7");
        jButton117.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton117ActionPerformed(evt);
            }
        });

        jButton118.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton118.setText("8");
        jButton118.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton118ActionPerformed(evt);
            }
        });

        jButton120.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton120.setText("-");
        jButton120.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton120ActionPerformed(evt);
            }
        });

        jButton119.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton119.setText("9");
        jButton119.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton119ActionPerformed(evt);
            }
        });

        jButton122.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton122.setText("4");
        jButton122.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton122ActionPerformed(evt);
            }
        });

        jButton123.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton123.setText("5");
        jButton123.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton123ActionPerformed(evt);
            }
        });

        jButton124.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton124.setText("6");
        jButton124.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton124ActionPerformed(evt);
            }
        });

        jButton125.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton125.setText("*");
        jButton125.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton125ActionPerformed(evt);
            }
        });

        jButton127.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton127.setText("1");
        jButton127.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton127ActionPerformed(evt);
            }
        });

        jButton130.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton130.setText("/");
        jButton130.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton130ActionPerformed(evt);
            }
        });

        jButton128.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton128.setText("2");
        jButton128.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton128ActionPerformed(evt);
            }
        });

        jButton129.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton129.setText("3");
        jButton129.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton129ActionPerformed(evt);
            }
        });

        jButton134.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton134.setText("=");
        jButton134.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton134ActionPerformed(evt);
            }
        });

        jButton132.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton132.setText("0");
        jButton132.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton132ActionPerformed(evt);
            }
        });

        jButton133.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton133.setText(".");
        jButton133.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton133ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton111, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton112, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton113, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton114, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton115, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton106, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton107, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton108, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jButton109, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton110, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton101, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jButton102, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton103, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jButton104, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton105, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton116, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton121, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton126, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton131, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton117, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton122, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton127, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton132, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton118, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton123, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton128, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton133, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jButton134, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton119, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton120, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton124, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton125, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton129, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton130, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton102, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton101, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton104, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton103, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton105, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton106, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton107, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton109, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton108, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton110, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton112, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton113, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton111, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton114, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton115, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton120, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton119, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton125, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton124, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton130, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton129, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton134, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton118, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton123, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton128, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton133, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton117, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton122, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton127, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton132, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton116, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton121, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton126, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton131, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        enable();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton2ActionPerformed
        disable();
    }// GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton102ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton102ActionPerformed
        double expResult = Math.exp(Double.parseDouble(jTextField1.getText()));
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + expResult);
    }// GEN-LAST:event_jButton102ActionPerformed

    private void jButton104ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton104ActionPerformed
        double trigCos = Math.cos(Math.toRadians(Double.parseDouble(jTextField1.getText())));
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + trigCos);
    }// GEN-LAST:event_jButton104ActionPerformed

    private void jButton105ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton105ActionPerformed
        double trigTan = Math.tan(Math.toRadians(Double.parseDouble(jTextField1.getText())));
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + trigTan);
    }// GEN-LAST:event_jButton105ActionPerformed

    private void jButton106ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton106ActionPerformed
        double num = 1 / (Double.parseDouble(jTextField1.getText()));
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + num);
    }// GEN-LAST:event_jButton106ActionPerformed

    private void jButton111ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton111ActionPerformed
        num1 = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        opr = "x^y";
    }// GEN-LAST:event_jButton111ActionPerformed

    private void jButton121ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton121ActionPerformed
        double num = Double.parseDouble(jTextField1.getText());
        num = num * num;
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + num);
    }// GEN-LAST:event_jButton121ActionPerformed

    private void jButton126ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton126ActionPerformed
        double num = Double.parseDouble(jTextField1.getText());
        double factoResult = 1;
        for (int i = 1; i <= num; i++) {
            factoResult *= i;
        }
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + factoResult);
    }// GEN-LAST:event_jButton126ActionPerformed

    private void jButton107ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton107ActionPerformed
        double logResult = Math.log(Double.parseDouble(jTextField1.getText()));
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + logResult);
    }// GEN-LAST:event_jButton107ActionPerformed

    private void jButton133ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton133ActionPerformed
        jTextField1.setText(jTextField1.getText() + ".");
    }// GEN-LAST:event_jButton133ActionPerformed

    private void jButton127ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton127ActionPerformed
        jTextField1.setText(jTextField1.getText() + "1");
    }// GEN-LAST:event_jButton127ActionPerformed

    private void jButton124ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton124ActionPerformed
        jTextField1.setText(jTextField1.getText() + "6");
    }// GEN-LAST:event_jButton124ActionPerformed

    private void jButton132ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton132ActionPerformed
        jTextField1.setText(jTextField1.getText() + "0");
    }// GEN-LAST:event_jButton132ActionPerformed

    private void jButton129ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton129ActionPerformed
        jTextField1.setText(jTextField1.getText() + "3");
    }// GEN-LAST:event_jButton129ActionPerformed

    private void jButton128ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton128ActionPerformed
        jTextField1.setText(jTextField1.getText() + "2");
    }// GEN-LAST:event_jButton128ActionPerformed

    private void jButton123ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton123ActionPerformed
        jTextField1.setText(jTextField1.getText() + "5");
    }// GEN-LAST:event_jButton123ActionPerformed

    private void jButton122ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton122ActionPerformed
        jTextField1.setText(jTextField1.getText() + "4");
    }// GEN-LAST:event_jButton122ActionPerformed

    private void jButton119ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton119ActionPerformed
        jTextField1.setText(jTextField1.getText() + "9");
    }// GEN-LAST:event_jButton119ActionPerformed

    private void jButton118ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton118ActionPerformed
        jTextField1.setText(jTextField1.getText() + "8");
    }// GEN-LAST:event_jButton118ActionPerformed

    private void jButton117ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton117ActionPerformed
        jTextField1.setText(jTextField1.getText() + "7");
    }// GEN-LAST:event_jButton117ActionPerformed

    private void jButton113ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton113ActionPerformed
        jTextField1.setText("");
    }// GEN-LAST:event_jButton113ActionPerformed

    private void jButton114ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton114ActionPerformed
        String backspace = null;
        if (jTextField1.getText().length() > 0) {
            StringBuilder s = new StringBuilder(jTextField1.getText());
            s.deleteCharAt(jTextField1.getText().length() - 1);
            backspace = s.toString();
            jTextField1.setText(backspace);
        }
    }// GEN-LAST:event_jButton114ActionPerformed

    private void jButton115ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton115ActionPerformed
        num1 = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        opr = "+";
    }// GEN-LAST:event_jButton115ActionPerformed

    private void jButton120ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton120ActionPerformed
        num1 = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        opr = "-";
    }// GEN-LAST:event_jButton120ActionPerformed

    private void jButton125ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton125ActionPerformed
        num1 = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        opr = "*";
    }// GEN-LAST:event_jButton125ActionPerformed

    private void jButton130ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton130ActionPerformed
        num1 = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        opr = "/";
    }// GEN-LAST:event_jButton130ActionPerformed

    private void jButton112ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton112ActionPerformed
        num1 = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        opr = "%";
    }// GEN-LAST:event_jButton112ActionPerformed

    private void jButton134ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton134ActionPerformed
        num2 = Double.parseDouble(jTextField1.getText());
        switch (opr) {
            case "+":
                result = num1 + num2;
                jTextField1.setText(Double.toString(result));
                break;
            case "-":
                result = num1 - num2;
                jTextField1.setText(Double.toString(result));
                break;
            case "*":
                result = num1 * num2;
                jTextField1.setText(Double.toString(result));
                break;
            case "/":
                result = num1 / num2;
                jTextField1.setText(Double.toString(result));
                break;
            case "%":
                result = num1 % num2;
                jTextField1.setText(Double.toString(result));
                break;
            case "x^y":
                result = 1;
                for (int i = 0; i < num2; i++) {
                    result *= num1;
                }
                jTextField1.setText(Double.toString(result));
                break;
            default:
                System.out.println("Error-unknown operator!");
        }
    }// GEN-LAST:event_jButton134ActionPerformed

    private void jButton103ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton103ActionPerformed
        double trigSin = Math.sin(Math.toRadians(Double.parseDouble(jTextField1.getText())));
        System.out.println(trigSin);
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + trigSin);

    }// GEN-LAST:event_jButton103ActionPerformed

    private void jButton108ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton108ActionPerformed
        double trigSinh = Math.sinh(Math.toRadians(Double.parseDouble(jTextField1.getText())));
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + trigSinh);
    }// GEN-LAST:event_jButton108ActionPerformed

    private void jButton109ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton109ActionPerformed
        double trigCosh = Math.cosh(Math.toRadians(Double.parseDouble(jTextField1.getText())));
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + trigCosh);
    }// GEN-LAST:event_jButton109ActionPerformed

    private void jButton110ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton110ActionPerformed
        double trigTanh = Math.tanh(Math.toRadians(Double.parseDouble(jTextField1.getText())));
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + trigTanh);
    }// GEN-LAST:event_jButton110ActionPerformed

    private void jButton101ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton101ActionPerformed
        double sqrtResult = Math.sqrt(Double.parseDouble(jTextField1.getText()));
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + sqrtResult);
    }// GEN-LAST:event_jButton101ActionPerformed

    private void jButton116ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton116ActionPerformed
        double num = Double.parseDouble(jTextField1.getText());
        num = num * num * num;
        jTextField1.setText("");
        jTextField1.setText(jTextField1.getText() + num);
    }// GEN-LAST:event_jButton116ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScientificCalc.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScientificCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton102;
    private javax.swing.JButton jButton103;
    private javax.swing.JButton jButton104;
    private javax.swing.JButton jButton105;
    private javax.swing.JButton jButton106;
    private javax.swing.JButton jButton107;
    private javax.swing.JButton jButton108;
    private javax.swing.JButton jButton109;
    private javax.swing.JButton jButton110;
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton112;
    private javax.swing.JButton jButton113;
    private javax.swing.JButton jButton114;
    private javax.swing.JButton jButton115;
    private javax.swing.JButton jButton116;
    private javax.swing.JButton jButton117;
    private javax.swing.JButton jButton118;
    private javax.swing.JButton jButton119;
    private javax.swing.JButton jButton120;
    private javax.swing.JButton jButton121;
    private javax.swing.JButton jButton122;
    private javax.swing.JButton jButton123;
    private javax.swing.JButton jButton124;
    private javax.swing.JButton jButton125;
    private javax.swing.JButton jButton126;
    private javax.swing.JButton jButton127;
    private javax.swing.JButton jButton128;
    private javax.swing.JButton jButton129;
    private javax.swing.JButton jButton130;
    private javax.swing.JButton jButton131;
    private javax.swing.JButton jButton132;
    private javax.swing.JButton jButton133;
    private javax.swing.JButton jButton134;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
